import Navbar from "@/components/Navbar";
import "../globals.css";
import { Inter } from "next/font/google";
import { Providers } from '../providers'
import { Sidebar } from "@/components/sidebar";
import { MobileHeader } from "@/components/mobile-header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body className={inter.className}> */}
      <body>
      <MobileHeader />
          <Sidebar classname="hidden lg:flex"/>
          <Providers>
          <div className=" lg:pl-[256px] h-full pt-[50px] lg:pt-0">
            <Navbar />
            <div className="max-w-[1056px] mx-auto pt-6 h-full ">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}