// // import Navbar from "@/components/Navbar";
// import "../globals.css";
// // import { Inter } from "next/font/google";
// // import Footer from "@/components/Footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="flex flex-col min-h-screen max-w-3xl mx-auto p-4">
//           <Navbar />
//           <main className="flex-grow mt-8">
//             {children}
//           </main>
//         </div>
//       </body>
//       <Footer/>
//     </html>
//   );
// }

import {Header} from "./header.jsx";
import { Footer } from "./footer.jsx";
import "../globals.css";

const MarketingLayout = ({ children }) => {
  return (
    <html lang="en">
    <body suppressHydrationWarning={true}>
    <div className="min-h-screen flex flex-col">
        <Header />
        <main className="flex-1 flex flex-col items-center justify-center">
            {children}
        </main>
        <Footer />
    </div>
    </body>
    </html>
  )};
  export default MarketingLayout;